import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import path from 'path';
import { readEnv, repoRoot } from './scripts/env.mjs';

// The version is baked as a placeholder and substituted after every rebuild
// with a FRESH read of manifest.json — a long-lived watch process must never
// serve the version that was current when it started.
const VERSION_PLACEHOLDER = '__TASKFLOW_VERSION_AT_BUILD__';
const readManifestVersion = () =>
	JSON.parse(readFileSync(path.join(repoRoot, 'manifest.json'), 'utf8')).version;

const stampVersion = {
	name: 'stamp-version',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			const outfile = path.join(repoRoot, 'main.js');
			if (!existsSync(outfile)) return;
			const content = readFileSync(outfile, 'utf8');
			writeFileSync(outfile, content.replaceAll(VERSION_PLACEHOLDER, readManifestVersion()));
		});
	},
};

// When TEST_VAULT_PATH is set, every (re)build copies the plugin files into
// the vault as real files; reload via the sidebar's ⟳ button (or toggling the
// plugin) to pick them up. Symlinks aren't used because Obsidian's file
// watcher doesn't reliably see changes through them.
function vaultPluginDir() {
	const raw = readEnv().TEST_VAULT_PATH ?? process.env.TEST_VAULT_PATH;
	if (!raw) return null;
	const vault = path.isAbsolute(raw) ? raw : path.resolve(repoRoot, raw);
	return path.join(vault, '.obsidian', 'plugins', 'taskflow-v2');
}

const copyToVault = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			const dir = vaultPluginDir();
			if (!dir || result.errors.length > 0) return;
			mkdirSync(dir, { recursive: true });
			for (const name of ['main.js', 'manifest.json', 'styles.css']) {
				const src = path.join(repoRoot, name);
				if (!existsSync(src)) continue;
				const dest = path.join(dir, name);
				try {
					if (lstatSync(dest).isSymbolicLink()) rmSync(dest);
				} catch {
					/* dest doesn't exist */
				}
				copyFileSync(src, dest);
			}
			console.log(`[taskflow-v2] copied build -> ${dir}`);
		});
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	jsx: 'automatic',
	plugins: [stampVersion, copyToVault],
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		// Placeholder — replaced with the fresh manifest version by the
		// stamp-version plugin after every rebuild (see above).
		__TASKFLOW_VERSION__: JSON.stringify(VERSION_PLACEHOLDER),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
